Update dependencies
AGP 8.2.2 is intentionally excluded because it appears to cause a
miscompilation that results in the following crash when loading the
byte code of the MediaCodecEncoder class:

java.lang.VerifyError: Verifier rejected class com.chiller3.bcr.format.MediaCodecEncoder: void com.chiller3.bcr.format.MediaCodecEncoder.encode(java.nio.ByteBuffer, boolean) failed to verify: void com.chiller3.bcr.format.MediaCodecEncoder.encode(java.nio.ByteBuffer, boolean): [0xCE] type Undefined unexpected as arg to if-eqz/if-nez

Signed-off-by: Andrew Gunnerson <accounts+github@chiller3.com>